#/bin/bash
for i in ALACHUA BAKER BAY BRADFORD BREVARD BROWARD CALHOUN CHARLOTTE CITRUS CLAY COLLIER COLUMBIA MIAMI-DADE DESOTO DIXIE DUVAL ESCAMBIA FLAGLER FRANKLIN GADSDEN GILCHRIST GLADES GULF HAMILTON HARDEE HENDRY HERNANDO HIGHLANDS HILLSBOROUGH HOLMES INDIAN_RIVER JACKSON JEFFERSON LAFAYETTE LAKE LEE LEON LEVY LIBERTY MADISON MANATEE MARION MARTIN MONROE NASSAU OKALOOSA OKEECHOBEE ORANGE OSCEOLA PALM_BEACH PASCO PINELLAS POLK PUTNAM ST_JOHNS ST_LUCIE SANTA_ROSA SARASOTA SEMINOLE SUMTER SUWANNEE TAYLOR UNION VOLUSIA WAKULLA WALTON WASHINGTON DEAF_BLIND FL_VIRTUAL FAU_LAB_SCH FSU_LAB_SCH FAMU_LAB_SCH UF_LAB_SCH
do
var1="$(ls ./School_plots/$i)"
echo -e "heading\r![](../School_plots/"$var1")" >> ./District_pages/"${i}_list".txt
done